name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Dijalankan setiap hari pada tengah malam UTC
  workflow_dispatch:     # Memungkinkan menjalankan workflow secara manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Generate Snake untuk tema terang (default)
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Mahiiru  # Ganti dengan username GitHub Anda
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'
      
      # Generate Snake untuk tema gelap
      - uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: Mahiiru  # Ganti dengan username GitHub Anda
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'
          color_snake: "#3c7dd9"
          color_dots: "#24292e,#394751,#4f6173,#6e7a8a,#8c99a8"
      
      # Push hasil ke branch output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output  # File SVG akan dikirim ke branch 'output'
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
